// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var flag;
    flag = 1;
    return $('#hover-button').click(function() {
      if (flag === 1) {
        alert("Please hover your mouse to the left side of the screen to access the menu!");
        flag = 0;
      } else {
        flag = 1;
      }
      $('.header').toggleClass('inactive');
      $('.footer').toggleClass('inactive');
      $('#signal').toggleClass('active');
      if ($(this).text() === "In-Active") {
        $(this).text("Active");
        return $('body').css('padding-bottom', '0px');
      } else {
        $(this).text("In-Active");
        return $('body').css('padding-bottom', "75px");
      }
    });
  });

}).call(this);
